propose:
  description: >
    You are proposing the motion: {motion}.
    Present a clear argument for the motion, using evidence and reasoning.
    come up with a compelling case, for the motion.
  expected_output: >
    Your argument should be well-structured, persuasive, and supported by relevant evidence.
  agent: debater
  output_file: output/propose.md

oppose:
  description: >
    You are opposing the motion: {motion}.
    Present a clear argument against the motion, using evidence and reasoning.
    come up with a compelling case, against the motion.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without
  agent: debater
  output_file: output/oppose.md

decide:
  description: >
    Review the arguments presented by the debaters and decide which side has the stronger case.
  expected_output: >
    A detailed analysis of the arguments presented, highlighting the strengths and weaknesses of each side.
    Provide a clear decision on which side won the debate, along with reasoning for your decision.
  agent: judge
  output_file: output/decide.md
